#!/bin/sh
#
# @name TUDa FSR EduFly
#
# @type Quadrotor x
# @class Copter
#
# @maintainer UAS Team FSR@TUDa <uas@fsr.tu-darmstadt.de>
#

. ${R}etc/init.d/rc.mc_defaults

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1

# Battery
param set-default BAT1_N_CELLS 4
param set-default BAT1_V_CHARGED 4.1500

# Micro XRCE DDS Agent
param set-default MAV_2_MODE 2
param set-default MAV_2_REMOTE_PRT 14540
param set-default MAV_2_UDP_PRT 14540
param set-default SER_TEL1_BAUD 115200
param set-default UXRCE_DDS_AG_IP -1062731775  # 192.168.0.2
param set-default UXRCE_DDS_CFG 1000

# Motor and Controller Tuning
param set-default MC_PITCHRATE_K 1.8000
param set-default MC_ROLLRATE_K 1.8000
param set-default MC_YAWRATE_K 1.7000
param set-default PWM_AUX_FUNC1 102
param set-default PWM_AUX_FUNC2 101
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104
param set-default PWM_AUX_MAX1 1900
param set-default PWM_AUX_MAX2 1900
param set-default PWM_AUX_MAX3 1900
param set-default PWM_AUX_MAX4 1900
param set-default PWM_AUX_MAX7 1900
param set-default PWM_AUX_MAX8 1900
param set-default PWM_AUX_MIN1 1100
param set-default PWM_AUX_MIN2 1100
param set-default PWM_AUX_MIN3 1100
param set-default PWM_AUX_MIN4 1100
param set-default PWM_AUX_MIN7 1100
param set-default PWM_AUX_MIN8 1100
param set-default PWM_AUX_TIM0 -3
param set-default PWM_MAIN_FUNC1 102
param set-default PWM_MAIN_FUNC2 101
param set-default PWM_MAIN_FUNC7 103
param set-default PWM_MAIN_FUNC8 104
param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_MAX2 1900
param set-default PWM_MAIN_MAX3 1900
param set-default PWM_MAIN_MAX4 1900
param set-default PWM_MAIN_MAX7 1900
param set-default PWM_MAIN_MAX8 1900
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100
param set-default PWM_MAIN_MIN7 1100
param set-default PWM_MAIN_MIN8 1100
param set-default THR_MDL_FAC 0.3000

# Range finder
# TODO: Add more ekf2 settings and enable conditional range aid
param set-default EKF2_RNG_A_HMAX 3.0000
param set-default EKF2_RNG_A_VMAX 1.5000

### Start range finder sensor
srf02 start -X -a 112
